---
abstract: 'debugging plugin to quickly dump out'
author:
  - "'Zoffix <'zoffix@cpan.org'>"
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-ZofCMS-Plugin-AutoDump
provides:
  App::ZofCMS::Plugin::AutoDump:
    file: lib/App/ZofCMS/Plugin/AutoDump.pm
    version: 0.0102
requires:
  Data::Dumper: 0
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
version: 0.0102
